language: node_js

node_js: stable

install:
  - npm install

script:
  - hexo g

after_success:
  - cd ./master
  - git add .
  - git commit -m "updated at $(date)"
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" HEAD:master

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/Eskibear/Eskibear.github.io.git
